apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system

spec:
  selector:
    app: sales

  type: ClusterIP

  ports:
  - name: sales-api
    port: 3000
    targetPort: sales-api
  - name: sales-api-debug
    port: 3499
    targetPort: sales-api-debug